default_language_version:
  python: python3.9
default_stages:
  - commit
  - push
exclude: >
  (?x)^(
      .*/migrations/[0-9]{4}_.*\.py
      | .*/alembic/.*\.py
      | alembic/env.py
      | .*test.*
      | gunicorn.conf.py
      | generate_setup_db.py
      | execute_alembic.py
      | main.py
      | .*/alembic/versions/.*\.py
      | alembic/versions/.*
      | generate_requirements.py
      | create_params/script.py
  )$
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8
          - --ignore=W503
        exclude: (tests|\.code_quality)
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - --rcfile=.code_quality/.pylintrc
        exclude: (tests|\.code_quality|main.py|setup.py)
        verbose: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.14
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.1
  #   hooks:
  #     - id: bandit
  #       args:
  #         - -c
  #         - .code_quality/bandit.yaml

