AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Description: Environment in which the resources will be deploy
    Type: AWS::SSM::Parameter::Value<String>
    Default: EnvironmentBtgPactual
  SQSBatchSize:
    Description: sqs batch size
    Type: AWS::SSM::Parameter::Value<String>
    Default: SQSBatchSizeBtgPactual
  AuthorizerTimeout:
    Description: authorizer timeout
    Type: AWS::SSM::Parameter::Value<String>
    Default: AuthorizerTimeoutBtgPactual
  DBSuffix:
    Description: dynamodb table suffix
    Type: AWS::SSM::Parameter::Value<String>
    Default: DBSuffixBtgPactual
  TokenExpiration:
    Description: token expiration
    Type: AWS::SSM::Parameter::Value<String>
    Default: TokenExpirationBtgPactual
  GlobalTimeout:
    Description: global timeout
    Type: AWS::SSM::Parameter::Value<String>
    Default: GlobalTimeoutBtgPactual
  DyanmoDBReadCapacityUnits:
    Description: dynamodb read capacity units
    Type: AWS::SSM::Parameter::Value<String>
    Default: DyanmoDBReadCapacityUnitsBtgPactual
  DyanmoDBWriteCapacityUnits:
    Description: dynamodb write capacity units
    Type: AWS::SSM::Parameter::Value<String>
    Default: DyanmoDBWriteCapacityUnitsBtgPactual
  SecretKey:
    Description: Secret Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: SecretKeyBtgPactual
  EnvAwsRegion:
    Description: Secret Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: EnvAwsRegionBtgPactual
  StackName:
    Description: Stack Name inmensity
    Type: AWS::SSM::Parameter::Value<String>
    Default: StackNameBtgPactual
  EnvBucketName:
    Description: Env aws access key
    Type: AWS::SSM::Parameter::Value<String>
    Default: EnvBucketNameBtgPactual
  RegionBucket:
    Description: Env aws region
    Type: AWS::SSM::Parameter::Value<String>
    Default: RegionBucketBtgPactual
  SendGridApiKey:
    Description: Send Grid Api Key
    Type: AWS::SSM::Parameter::Value<String>
    Default: SendGridApiKeyBtgPactual
  FromEmail:
    Description: From Email
    Type: AWS::SSM::Parameter::Value<String>
    Default: FromEmailBtgPactual
Resources:
  # Layer stack
  LayerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: template_layers.yaml
      Parameters:
        StackName: !Ref StackName
        Environment: !Ref Environment
      TimeoutInMinutes: 10

  # Dynamo Stack
  DynamoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: template_dynamo.yaml
      Parameters:
        StackName: !Ref StackName
        Environment: !Ref Environment
        DyanmoDBReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
        DyanmoDBWriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits
      TimeoutInMinutes: 10

  # Authorizer Stack
  AuthorizerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: template_authorizer.yaml
      Parameters:
        GlobalTimeout: !Ref GlobalTimeout
        Environment: !Ref Environment
        SecretKey: !Ref SecretKey
        StackName: !Ref StackName
        # Layer
        LayerDependencies: !GetAtt LayerStack.Outputs.LayerDependencies
        # Dynamo
        DynamoTableName: !GetAtt DynamoStack.Outputs.DynamoTableName
      TimeoutInMinutes: 10

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: template.yaml
      Parameters:
        Environment: !Ref Environment
        SecretKey: !Ref SecretKey
        Environment: !Ref Environment
        EnvAwsRegion: !Ref EnvAwsRegion
        GlobalTimeout: !Ref GlobalTimeout
        TokenExpiration: !Ref TokenExpiration
        AuthorizerTimeout: !Ref AuthorizerTimeout
        SQSBatchSize: !Ref SQSBatchSize
        EnvBucketName: !Ref EnvBucketName
        RegionBucket: !Ref RegionBucket
        SendGridApiKey: !Ref SendGridApiKey
        FromEmail: !Ref FromEmail
        StackName: !Ref StackName
        # Layer
        LayerDependencies: !GetAtt LayerStack.Outputs.LayerDependencies
        # Dynamo
        DynamoTableName: !GetAtt DynamoStack.Outputs.DynamoTableName
        UsersTableName: !GetAtt DynamoStack.Outputs.UsersTableName
        TransactionsTableName: !GetAtt DynamoStack.Outputs.TransactionsTableName
        FoundsTableName: !GetAtt DynamoStack.Outputs.FoundsTableName
        AuthorizerArn: !GetAtt AuthorizerStack.Outputs.AuthorizerArn
      TimeoutInMinutes: 10
