AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack Microservices


Parameters:
  StackName:
    Description: stack Name
    Type: String
    Default: inmensity-stack-name
  Environment:
    Description: Environment in which the resources will be deploy
    Type: String
    Default: development
  DyanmoDBReadCapacityUnits:
    Description: dynamodb read capacity units
    Type: String
    Default: 5
  DyanmoDBWriteCapacityUnits:
    Description: dynamodb write capacity units
    Type: String
    Default: 5

Resources:

  AuthorizersDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbAuthoTable${Environment}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits
  
  UsersDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbAuthoTableUsers${Environment}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: Email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
            WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits

  TransactionsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbAuthoTableTransactions${Environment}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: found_type
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: User-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
            WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits
        - IndexName: Found-index
          KeySchema:
            - AttributeName: found_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
            WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits

  FoundsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbAuthoTableFounds${Environment}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DyanmoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DyanmoDBWriteCapacityUnits

Outputs:
  DynamoTableName:
    Value: !Sub DbAuthoTable${Environment}
    Export:
      Name: !Sub DbAuthoTable${Environment}
  UsersTableName:
    Value: !Sub DbAuthoTableUsers${Environment}
    Export:
      Name: !Sub DbAuthoTableUsers${Environment}
  TransactionsTableName:
    Value: !Sub DbAuthoTableTransactions${Environment}
    Export:
      Name: !Sub DbAuthoTableTransactions${Environment}
  FoundsTableName:
    Value: !Sub DbAuthoTableFounds${Environment}
    Export:
      Name: !Sub DbAuthoTableFounds${Environment}