version: '3.5'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile.testing
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    depends_on:
      - db_postgres_local
    restart: on-failure
  db_postgres_local:
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev-db-data-postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db_postgres_local
volumes:
  dev-db-data-postgres:
