"""init model

Revision ID: 48d136833c0f
Revises:
Create Date: 2024-04-16 14:37:16.037411

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48d136833c0f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("last_name", sa.String(length=200), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("recovery_hash", sa.String(length=255), nullable=True),
        sa.Column("data_treatment", sa.Boolean(), nullable=True),
        sa.Column("terms_conditions", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
